// Package contract serves the OpenAPI 3 description of this API.
package contract

import (
	_ "embed"
	"net/http"
)

//go:embed openapi3.json
var spec []byte

// Spec is the OpenAPI 3 description of this API, generated by `sklp run
// generate` and committed alongside the handlers it describes.
//
// It is embedded rather than read from disk so the running binary can only
// serve the contract it was built from: a file loaded at boot could be swapped
// for one describing routes this binary does not have.
func Spec() []byte { return spec }

// Handler publishes the contract so a consumer generates its client from what
// vvaves actually serves, instead of being handed a copy.
//
// A copy nobody is forced to refresh goes stale silently: packages/go/search's
// tornade client was written against /search alone and never learned that
// /map and /crawl exist, and the README documented eight routes out of twelve
// for as long. Serving the contract removes the reason either could drift.
func Handler() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Write(spec)
	}
}
