/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAppsRouteImport } from './routes/admin/apps'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as AppKeysRouteImport } from './routes/app/keys'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiAuthSsoRouteImport } from './routes/api/auth/sso'
import { Route as ApiKeysIndexRouteImport } from './routes/api/keys.index'
import { Route as ApiKeysIdRouteImport } from './routes/api/keys.$id'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiAdminUsersUserIdRouteImport } from './routes/api/admin/users.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppsRoute = AdminAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AppKeysRoute = AppKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSsoRoute = ApiAuthSsoRouteImport.update({
  id: '/api/auth/sso',
  path: '/api/auth/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysIndexRoute = ApiKeysIndexRouteImport.update({
  id: '/api/keys/',
  path: '/api/keys/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysIdRoute = ApiKeysIdRouteImport.update({
  id: '/api/keys/$id',
  path: '/api/keys/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersUserIdRoute = ApiAdminUsersUserIdRouteImport.update({
  id: '/api/admin/users/$userId',
  path: '/api/admin/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/apps': typeof AdminAppsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/me': typeof ApiMeRoute
  '/app/keys': typeof AppKeysRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/sso': typeof ApiAuthSsoRoute
  '/api/keys/$id': typeof ApiKeysIdRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/keys/': typeof ApiKeysIndexRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/apps': typeof AdminAppsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/me': typeof ApiMeRoute
  '/app/keys': typeof AppKeysRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/sso': typeof ApiAuthSsoRoute
  '/api/keys/$id': typeof ApiKeysIdRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/keys': typeof ApiKeysIndexRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/apps': typeof AdminAppsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin_/login': typeof AdminLoginRoute
  '/api/me': typeof ApiMeRoute
  '/app/keys': typeof AppKeysRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/sso': typeof ApiAuthSsoRoute
  '/api/keys/$id': typeof ApiKeysIdRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/keys/': typeof ApiKeysIndexRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/apps'
    | '/admin/users'
    | '/admin/login'
    | '/api/me'
    | '/app/keys'
    | '/admin/'
    | '/api/auth/$'
    | '/api/auth/sso'
    | '/api/keys/$id'
    | '/api/v1/$'
    | '/api/keys/'
    | '/api/admin/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/admin/apps'
    | '/admin/users'
    | '/admin/login'
    | '/api/me'
    | '/app/keys'
    | '/admin'
    | '/api/auth/$'
    | '/api/auth/sso'
    | '/api/keys/$id'
    | '/api/v1/$'
    | '/api/keys'
    | '/api/admin/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/apps'
    | '/admin/users'
    | '/admin_/login'
    | '/api/me'
    | '/app/keys'
    | '/admin/'
    | '/api/auth/$'
    | '/api/auth/sso'
    | '/api/keys/$id'
    | '/api/v1/$'
    | '/api/keys/'
    | '/api/admin/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiMeRoute: typeof ApiMeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthSsoRoute: typeof ApiAuthSsoRoute
  ApiKeysIdRoute: typeof ApiKeysIdRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiKeysIndexRoute: typeof ApiKeysIndexRoute
  ApiAdminUsersUserIdRoute: typeof ApiAdminUsersUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/apps': {
      id: '/admin/apps'
      path: '/apps'
      fullPath: '/admin/apps'
      preLoaderRoute: typeof AdminAppsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/keys': {
      id: '/app/keys'
      path: '/keys'
      fullPath: '/app/keys'
      preLoaderRoute: typeof AppKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sso': {
      id: '/api/auth/sso'
      path: '/api/auth/sso'
      fullPath: '/api/auth/sso'
      preLoaderRoute: typeof ApiAuthSsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys/': {
      id: '/api/keys/'
      path: '/api/keys'
      fullPath: '/api/keys/'
      preLoaderRoute: typeof ApiKeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys/$id': {
      id: '/api/keys/$id'
      path: '/api/keys/$id'
      fullPath: '/api/keys/$id'
      preLoaderRoute: typeof ApiKeysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/$userId': {
      id: '/api/admin/users/$userId'
      path: '/api/admin/users/$userId'
      fullPath: '/api/admin/users/$userId'
      preLoaderRoute: typeof ApiAdminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAppsRoute: typeof AdminAppsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppsRoute: AdminAppsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppKeysRoute: typeof AppKeysRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppKeysRoute: AppKeysRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiMeRoute: ApiMeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthSsoRoute: ApiAuthSsoRoute,
  ApiKeysIdRoute: ApiKeysIdRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiKeysIndexRoute: ApiKeysIndexRoute,
  ApiAdminUsersUserIdRoute: ApiAdminUsersUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
