// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/apps": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Every registered application, key withheld",
                "operationId": "listApps",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/registry.AppListDTO"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Admit an application and hand its key out once",
                "operationId": "registerApp",
                "parameters": [
                    {
                        "description": "The issuer name the application signs as",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/registry.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/registry.CredentialsDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/registry.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/apps/{name}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "End an application's access at once",
                "operationId": "revokeApp",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/registry.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/apps/{name}/rotate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Mint an application a new key; the old one works for a day",
                "operationId": "rotateAppKey",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/registry.CredentialsDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/registry.ErrorDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/registry.ErrorDTO"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ops"
                ],
                "summary": "Liveness",
                "operationId": "healthz",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.healthResponse"
                        }
                    }
                }
            }
        },
        "/speak": {
            "post": {
                "security": [
                    {
                        "ServiceKey": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Answers audio bytes, not JSON. With stream=false the whole\nreading comes back with a Content-Length and ranges; with\nstream=true each piece is emitted as it is read, length-prefixed\nunder application/x-lalter-audio-frames.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "audio/mpeg"
                ],
                "tags": [
                    "speak"
                ],
                "summary": "Read a text aloud, from the store when it is already there",
                "operationId": "speak",
                "parameters": [
                    {
                        "description": "text to read",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpapi.speakRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    }
                }
            }
        },
        "/speak/exists": {
            "post": {
                "security": [
                    {
                        "ServiceKey": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "speak"
                ],
                "summary": "Whether a reading is already stored, without reading its bytes",
                "operationId": "speakExists",
                "parameters": [
                    {
                        "description": "reading to look for",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpapi.speakRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.existsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    }
                }
            }
        },
        "/speak/pregenerate": {
            "post": {
                "security": [
                    {
                        "ServiceKey": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "For a text expected to be heard more than once. It holds a\nsynthesis slot, so prefer /speak/prime for a text that may never\nbe played. Takes an application key.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "speak"
                ],
                "summary": "Read a whole text ahead of time and keep it",
                "operationId": "pregenerateSpeak",
                "parameters": [
                    {
                        "description": "text to read in full",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpapi.speakRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    }
                }
            }
        },
        "/speak/prime": {
            "post": {
                "security": [
                    {
                        "ServiceKey": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Answers 202 without waiting: nobody is listening yet. Takes an\napplication key — a browser signature is good for /speak alone.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "speak"
                ],
                "summary": "Read a text's opening ahead of time, so the first listen starts at once",
                "operationId": "primeSpeak",
                "parameters": [
                    {
                        "description": "text whose opening to read",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpapi.speakRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httpapi.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "httpapi.existsResponse": {
            "type": "object",
            "properties": {
                "ready": {
                    "type": "boolean"
                }
            }
        },
        "httpapi.healthResponse": {
            "type": "object",
            "properties": {
                "ok": {
                    "type": "boolean"
                }
            }
        },
        "httpapi.speakRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "scope": {
                    "description": "Scope and ID name where a reading is kept. Both optional: an ID lets a\ncaller prime a reading before anyone asks for it, since priming means\nnaming ahead of time what will be listened to. Without one the reading\nis still cached, keyed by the text alone — a second listen of the same\nwords finds it, which no caller has to opt into.",
                    "type": "string"
                },
                "stream": {
                    "type": "boolean"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "registry.AppDTO": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "grace_until": {
                    "type": "string"
                },
                "last4": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "revoked_at": {
                    "type": "string"
                },
                "rotated_at": {
                    "type": "string"
                }
            }
        },
        "registry.AppListDTO": {
            "type": "object",
            "properties": {
                "apps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registry.AppDTO"
                    }
                }
            }
        },
        "registry.CredentialsDTO": {
            "type": "object",
            "properties": {
                "grace_until": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "registry.ErrorDTO": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "registry.RegisterRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "ServiceKey": {
            "type": "apiKey",
            "name": "X-Vvaves-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.3.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Vvaves",
	Description:      "Read text aloud for every product, plus the admin API of the applications registry.\n\nThe speak routes answer at the root; the admin API is under\n/api/v1, which is why no global base path is declared.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
